# Generated by Django 5.2.17 on 2026-09-18 09:29

import django.db.models.deletion
from django.db import migrations, models


def seed_leave_types(apps, schema_editor):
    leave_type = apps.get_model("vacation", "LeaveTypeModel")
    leave_type.objects.bulk_create(
        [
            leave_type(type_id="ANNUAL", type_name="연차", is_paid=True, deduct_days=1),
            leave_type(type_id="HALF", type_name="반차", is_paid=True, deduct_days=0.5),
            leave_type(type_id="SICK", type_name="병가", is_paid=True, deduct_days=0),
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaveTypeModel",
            fields=[
                ("type_id", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=50, unique=True)),
                ("is_paid", models.BooleanField(default=True)),
                ("deduct_days", models.DecimalField(decimal_places=2, default=1, max_digits=3)),
            ],
            options={
                "db_table": "leave_types",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("deduct_days__gte", 0)),
                        name="leave_type_deduct_days_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequestModel",
            fields=[
                ("request_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("employee_no", models.IntegerField(db_column="emp_no")),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("use_days", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("승인", "승인"),
                            ("반려", "반려"),
                            ("취소", "취소"),
                            ("회수", "회수"),
                        ],
                        default="대기",
                        max_length=20,
                    ),
                ),
                ("approver_no", models.IntegerField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, max_length=255, null=True)),
                ("request_reason", models.TextField(blank=True, null=True)),
                (
                    "vacation_type",
                    models.ForeignKey(
                        db_column="type_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests",
                        to="vacation.leavetypemodel",
                    ),
                ),
            ],
            options={
                "db_table": "leave_requests",
                "ordering": ["-request_id"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequestHistoryModel",
            fields=[
                ("history_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("대기", "대기"),
                            ("승인", "승인"),
                            ("반려", "반려"),
                            ("취소", "취소"),
                            ("회수", "회수"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("승인", "승인"),
                            ("반려", "반려"),
                            ("취소", "취소"),
                            ("회수", "회수"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_employee_no", models.IntegerField(db_column="actor_emp_no")),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("changed_at", models.DateTimeField()),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="history_entries",
                        to="vacation.leaverequestmodel",
                    ),
                ),
            ],
            options={
                "db_table": "leave_request_history",
                "ordering": ["changed_at", "history_id"],
                "indexes": [
                    models.Index(fields=["request", "changed_at"], name="leave_hist_req_time_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="leaverequestmodel",
            index=models.Index(fields=["employee_no", "status"], name="leave_req_emp_status_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequestmodel",
            index=models.Index(fields=["approver_no", "status"], name="leave_req_appr_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="leaverequestmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("use_days__gt", 0)), name="leave_request_days_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequestmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_datetime__gte", models.F("start_datetime"))),
                name="leave_request_period_valid",
            ),
        ),
        migrations.RunPython(seed_leave_types, migrations.RunPython.noop),
    ]
