# Generated by Django 5.2.17 on 2026-09-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacation", "0001_initial"),
        ("workforce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBalanceModel",
            fields=[
                ("balance_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("remaining_days", models.DecimalField(decimal_places=2, max_digits=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_no",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="leave_balances",
                        to="workforce.employee",
                    ),
                ),
                (
                    "vacation_type",
                    models.ForeignKey(
                        db_column="type_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="employee_balances",
                        to="vacation.leavetypemodel",
                    ),
                ),
            ],
            options={
                "db_table": "leave_balances",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "vacation_type"),
                        name="leave_balance_employee_type_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("remaining_days__gte", 0)),
                        name="leave_balance_days_nonnegative",
                    ),
                ],
            },
        ),
    ]
