from typing import Protocol

from workforce.domain.policies import EmployeeCandidate


class WorkforceQueryGateway(Protocol):
    def has_active_role(self, employee_no: int, role_code: str) -> bool: ...

    def department_head(self, employee_no: int) -> EmployeeCandidate | None: ...

    def active_role_holders(self, role_code: str, *, limit: int) -> list[EmployeeCandidate]: ...


class RoleCommandGateway(Protocol):
    def employee_is_active(self, employee_no: int) -> bool: ...

    def has_active_assignment(self, employee_no: int, role_code: str) -> bool: ...

    def active_role_holder_count(self, role_code: str) -> int: ...

    def assign_role(self, employee_no: int, role_code: str) -> int: ...

    def revoke_role(self, employee_no: int, assignment_id: int) -> bool: ...
