# Hand-written (not autogenerated): board_posts and board_notice_categories already exist in
# the shared ERP database. This migration only registers their model state with Django and must
# not create or alter them.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workforce", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="NoticeCategoryModel",
                    fields=[
                        (
                            "notice_category_code",
                            models.CharField(max_length=20, primary_key=True, serialize=False),
                        ),
                        ("category_name", models.CharField(max_length=50)),
                    ],
                    options={
                        "db_table": "board_notice_categories",
                    },
                ),
                migrations.CreateModel(
                    name="PostModel",
                    fields=[
                        ("post_id", models.BigAutoField(primary_key=True, serialize=False)),
                        (
                            "post_type",
                            models.CharField(
                                choices=[("일반", "일반"), ("공지", "공지")],
                                default="일반",
                                max_length=10,
                            ),
                        ),
                        ("title", models.CharField(max_length=100)),
                        ("content", models.TextField()),
                        ("created_at", models.DateTimeField()),
                        ("updated_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "writer",
                            models.ForeignKey(
                                db_column="writer_emp_no",
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="board_posts",
                                to="workforce.employee",
                            ),
                        ),
                        (
                            "notice_category",
                            models.ForeignKey(
                                blank=True,
                                db_column="notice_category_code",
                                null=True,
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="posts",
                                to="board.noticecategorymodel",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "board_posts",
                        "ordering": ["-post_id"],
                    },
                ),
            ],
        ),
    ]
