# Generated by Django 5.2.17 on 2026-09-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_employee_no', models.IntegerField(db_column='author_emp_no')),
                ('post_type', models.CharField(choices=[('일반', '일반'), ('공지', '공지')], max_length=10)),
                ('notice_category', models.CharField(blank=True, choices=[('경영', '경영'), ('인사', '인사'), ('급여', '급여'), ('부서', '부서')], max_length=10, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board_posts',
                'ordering': ['-post_id'],
                'indexes': [models.Index(fields=['post_type', 'deleted_at'], name='board_post_type_del_idx'), models.Index(fields=['notice_category'], name='board_post_category_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('notice_category__isnull', True), ('post_type', '일반')), models.Q(('notice_category__isnull', False), ('post_type', '공지')), _connector='OR'), name='board_post_notice_category_matches_type')],
            },
        ),
    ]
