# Generated by Django 5.2.17 on 2026-10-01 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
        ("workforce", "0002_required_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                ("comment_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_comment_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="board.commentmodel",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="board.postmodel",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        db_column="writer_emp_no",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="board_comments",
                        to="workforce.employee",
                    ),
                ),
            ],
            options={
                "db_table": "board_comments",
                "ordering": ["created_at", "comment_id"],
            },
        ),
    ]
