# Generated by Django 5.2.17 on 2026-09-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workforce", "0003_payroll_manager_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollComponentTypeModel",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(choices=[("지급", "지급"), ("공제", "공제")], max_length=10),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_component_types",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="PublicHolidayModel",
            fields=[
                ("holiday_date", models.DateField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "payroll_public_holidays",
                "ordering": ["holiday_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollStatementModel",
            fields=[
                ("statement_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("period", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("작성중", "작성중"), ("확정", "확정")],
                        default="작성중",
                        max_length=10,
                    ),
                ),
                ("total_earnings", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("created_by", models.IntegerField(db_column="created_by_emp_no")),
                (
                    "confirmed_by",
                    models.IntegerField(blank=True, db_column="confirmed_by_emp_no", null=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_no",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payroll_statements",
                        to="workforce.employee",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_statements",
                "ordering": ["-period", "employee_id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollItemModel",
            fields=[
                ("item_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(choices=[("지급", "지급"), ("공제", "공제")], max_length=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "component",
                    models.ForeignKey(
                        db_column="component_code",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="items",
                        to="payroll.payrollcomponenttypemodel",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        db_column="statement_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="items",
                        to="payroll.payrollstatementmodel",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_items",
                "ordering": ["statement_id", "component_id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollHistoryModel",
            fields=[
                ("history_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=20)),
                ("actor_employee_no", models.IntegerField(db_column="actor_emp_no")),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("change_summary", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField()),
                (
                    "statement",
                    models.ForeignKey(
                        db_column="statement_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="history_entries",
                        to="payroll.payrollstatementmodel",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_history",
                "ordering": ["changed_at", "history_id"],
            },
        ),
        migrations.AddIndex(
            model_name="payrollstatementmodel",
            index=models.Index(fields=["employee", "status"], name="payroll_stmt_emp_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="payrollstatementmodel",
            constraint=models.UniqueConstraint(
                fields=("employee", "period"), name="payroll_statement_employee_period_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollitemmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="payroll_item_amount_nonnegative"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollhistorymodel",
            index=models.Index(
                fields=["statement", "changed_at"], name="payroll_hist_stmt_time_idx"
            ),
        ),
    ]
