# Generated by Django 5.2.17 on 2026-09-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            # These tables already exist in the shared ERP database. This migration only
            # registers their model state with Django and must not recreate them.
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Person",
                    fields=[
                        ("person_id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("name", models.CharField(max_length=50)),
                        ("birth_date", models.DateField(blank=True, null=True)),
                        ("gender", models.CharField(blank=True, max_length=1, null=True)),
                    ],
                    options={
                        "db_table": "persons",
                    },
                ),
                migrations.CreateModel(
                    name="Position",
                    fields=[
                        (
                            "position_code",
                            models.CharField(max_length=20, primary_key=True, serialize=False),
                        ),
                        ("position_name", models.CharField(max_length=50)),
                        ("sort_order", models.IntegerField(default=0)),
                    ],
                    options={
                        "db_table": "positions",
                        "ordering": ["sort_order", "position_code"],
                    },
                ),
                migrations.CreateModel(
                    name="Role",
                    fields=[
                        (
                            "role_code",
                            models.CharField(max_length=30, primary_key=True, serialize=False),
                        ),
                        ("role_name", models.CharField(max_length=50)),
                    ],
                    options={
                        "db_table": "roles",
                        "ordering": ["role_code"],
                    },
                ),
                migrations.CreateModel(
                    name="Department",
                    fields=[
                        ("dept_no", models.IntegerField(primary_key=True, serialize=False)),
                        ("dept_name", models.CharField(max_length=100)),
                        (
                            "parent",
                            models.ForeignKey(
                                blank=True,
                                db_column="parent_dept_no",
                                null=True,
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="children",
                                to="workforce.department",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "departments",
                        "ordering": ["dept_no"],
                    },
                ),
                migrations.CreateModel(
                    name="Employee",
                    fields=[
                        (
                            "employee_no",
                            models.IntegerField(
                                db_column="emp_no", primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "tenure_status",
                            models.CharField(
                                choices=[("재직", "재직"), ("휴직", "휴직"), ("퇴사", "퇴사")],
                                max_length=20,
                            ),
                        ),
                        ("phone", models.CharField(blank=True, max_length=20, null=True)),
                        (
                            "email",
                            models.EmailField(blank=True, max_length=100, null=True, unique=True),
                        ),
                        ("hire_date", models.DateField()),
                        ("term_date", models.DateField(blank=True, null=True)),
                        (
                            "extension_no",
                            models.CharField(
                                blank=True, db_column="ext_no", max_length=20, null=True
                            ),
                        ),
                        ("address", models.CharField(blank=True, max_length=255, null=True)),
                        ("bank_code", models.CharField(blank=True, max_length=20, null=True)),
                        ("account_no", models.CharField(blank=True, max_length=100, null=True)),
                        (
                            "department",
                            models.ForeignKey(
                                blank=True,
                                db_column="dept_no",
                                null=True,
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="employees",
                                to="workforce.department",
                            ),
                        ),
                        (
                            "person",
                            models.ForeignKey(
                                db_column="person_id",
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="employments",
                                to="workforce.person",
                            ),
                        ),
                        (
                            "position",
                            models.ForeignKey(
                                blank=True,
                                db_column="position_code",
                                null=True,
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="employees",
                                to="workforce.position",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "employees",
                        "ordering": ["employee_no"],
                    },
                ),
                migrations.AddField(
                    model_name="department",
                    name="head",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="head_emp_no",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to="workforce.employee",
                    ),
                ),
                migrations.CreateModel(
                    name="EmploymentHistory",
                    fields=[
                        ("history_id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("start_date", models.DateField()),
                        ("end_date", models.DateField(blank=True, null=True)),
                        (
                            "base_salary",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=15, null=True
                            ),
                        ),
                        (
                            "department",
                            models.ForeignKey(
                                db_column="dept_no",
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="employment_history",
                                to="workforce.department",
                            ),
                        ),
                        (
                            "employee",
                            models.ForeignKey(
                                db_column="emp_no",
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="employment_history",
                                to="workforce.employee",
                            ),
                        ),
                        (
                            "position",
                            models.ForeignKey(
                                db_column="position_code",
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="employment_history",
                                to="workforce.position",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "emp_history",
                        "ordering": ["employee_id", "-start_date"],
                    },
                ),
                migrations.CreateModel(
                    name="EmployeeRole",
                    fields=[
                        (
                            "employee_role_id",
                            models.BigAutoField(primary_key=True, serialize=False),
                        ),
                        ("assigned_at", models.DateTimeField()),
                        ("revoked_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "employee",
                            models.ForeignKey(
                                db_column="emp_no",
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="role_assignments",
                                to="workforce.employee",
                            ),
                        ),
                        (
                            "role",
                            models.ForeignKey(
                                db_column="role_code",
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="employee_assignments",
                                to="workforce.role",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "employee_roles",
                        "ordering": ["employee_id", "role_id", "-assigned_at"],
                    },
                ),
            ],
        ),
    ]
