# Generated by Django 5.2.17 on 2026-10-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workforce", "0002_required_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfoChangeRequest",
            fields=[
                ("request_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("previous_email", models.CharField(blank=True, max_length=100, null=True)),
                ("previous_bank_code", models.CharField(blank=True, max_length=20, null=True)),
                ("previous_account_no", models.CharField(blank=True, max_length=100, null=True)),
                ("requested_email", models.CharField(blank=True, max_length=100, null=True)),
                ("requested_bank_code", models.CharField(blank=True, max_length=20, null=True)),
                ("requested_account_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("승인", "승인"),
                            ("반려", "반려"),
                            ("취소", "취소"),
                        ],
                        default="대기",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_no",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="personal_info_change_requests",
                        to="workforce.employee",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="processed_by_emp_no",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="processed_personal_info_change_requests",
                        to="workforce.employee",
                    ),
                ),
            ],
            options={
                "db_table": "personal_info_change_requests",
                "ordering": ["-requested_at", "-request_id"],
                "indexes": [
                    models.Index(fields=["employee", "status"], name="pi_change_req_emp_status_idx")
                ],
            },
        ),
    ]
